### ISSUE TITLE
iOS 15 Support

### ISSUE THREAD

**Issue by kronos-99** [waresnew/badgesync#3]
This looks like a great tweak, and was wondering if there is anyway to make it compatible with roothide dopamine? i tried to convert it, but it does not work unfortunately. Thank you!

EDIT: I'm unsure if its an issue with roothide dopamine or iOS 15. Another user and myself were hoping you could make it iOS 15 compatible. Thank you!

**Comment by waresnew** [comment]
Hi, I'm pretty sure this tweak should convert properly to Roothide, since it doesn't access any files.

iOS 15 support is something I've been looking at for a while (and iOS 17), but I only have an iOS 16 device.

Also, how'd you install this tweak on iOS 15? I added a requirement that the iOS version has to be at least 16.0 in the package, so Sileo/other package manager should've blocked that.

If I can just change the minimum version for it to work, then I can probably support 15 pretty easily, otherwise I probably have to search for the correct methods to hook again, which might take a while since I don't have a device with iOS 15.

**Comment by kronos-99** [comment]
I wasn't able to install on 15. it gives me a dependency error. ![image](https://github.com/user-attachments/assets/a97a50a5-655d-43e8-a095-7d5f90b83b53)

**Comment by waresnew** [comment]
Oh ok, I'll have to spend some time to check if all the classes/methods I use exist in iOS 15 first, before it can be tested. (it might take a while).

I can't really test it myself since I don't have an iOS 15 device, so I only can check if it theoretically would work.

When I'm done checking, would you be willing to test it?

**Comment by waresnew** [comment]
It looks like all the methods I use exist all the way back to iOS 14.0 so that's pretty convenient

So that means the tweak should work on 14 and 15 without changing any of the code (except the version requirement)

If you're comfortable with it, can you test if this version of the tweak works? I compiled it for Roothide and set the minimum version to iOS 14.

Your phone might safemode (eg. when your status bar is red) or respring loop if it doesn't work out though, but rebooting your phone should fix it.

(Github doesn't allow me to attach deb files so I had to zip it)

[extractthis.zip](https://github.com/user-attachments/files/16640915/extractthis.zip)

**Comment by kronos-99** [comment]
i was able to install it with no issues but, no new badges are showing now. tested it with messages. i get new messages, still in notification center but no badge on messages app.

**Comment by kronos-99** [comment]
update: if i check notification on lockscreen and don't delete it, then badge shows on app once i unlock phone. when i delete notification on lock screen/notification center, it then clears badge. hopefully that makes sense. so a small bug it seems, lmk how i can help, thank you

**Comment by waresnew** [comment]
hm i got my hands on an ipad on 15.8 today and it worked completely fine for me (no roothide since my version doesn't support it, but i don't think roothide would change anything) (tested on the Mail app bc i didn't have imessage)

this is a bit of a shot in the dark but i changed something and it might work

[extract.zip](https://github.com/user-attachments/files/16663744/extract.zip)

alternatively:

are you familiar with viewing device logs? you can plug your phone into your computer via usb, download [this](https://github.com/libimobiledevice/libimobiledevice), and run `idevicesyslog.exe -m "BadgeSync"` in the terminal

it'll show some basic logging

![image](https://github.com/user-attachments/assets/5924584e-cf1b-427a-b62e-9dcb0c3eb611)

(eg. when a notification appears, a line starting with `Insert:` will be logged followed by `SETTER:` that indicates what the badge was set to; when a notification is cleared it'll log `Remove:` along with `SETTER`

if you see what gets printed at the moment you get a notif/clear a notif then it might give some hints

**Comment by kronos-99** [comment]
the 2nd deb caused safe mode, the first one works okay when i disabled axon (rootless). so it looks like it doesn't like axon, thank you very much!

**Comment by waresnew** [comment]
> the 2nd deb caused safe mode, the first one works okay when i disabled axon (rootless). so it looks like it doesn't like axon, thank you very much!

yeah i found a bug in the 2nd deb and fixed it after lol

it probably didn't work with axon bc my tweak queries the notification list but i think axon replaces it with their own structure

i might try to find someone with ios14 as well before i release all these changes since it should theoretically work on ios14 too

**Comment by kronos-99** [comment]
sounds great, appreciate you looking into and letting me test it out. thank you

**Comment by waresnew** [comment]
it turns out axon compatibility was pretty easy to add

i ran into some issues when i tried compiling with roothide so i think you have to convert it from now on

**Comment by waresnew** [comment]
found a tester with ios14 and they said it works!

1.2.0 will include this feature
